#!/bin/sh
### BEGIN INIT INFO
# Provides: unicorn
# Required-Start: $all
# Required-Stop: $network $local_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start the APPLICATION unicorns at boot
# Description: Enable APPLICATION at boot time.
### END INIT INFO

APP_NAME="APPLICATION"
APP_USER="www"
ENV=production

USER_HOME="/srv/$APP_USER"
APP_ROOT="$USER_HOME/$APP_NAME/current"
PID="$APP_ROOT/tmp/pids/unicorn.pid"
UNICORN_OPTS="-D -E $ENV -c $APP_ROOT/config/unicorn.rb"
SET_PATH="source /srv/$APP_USER/.rvm/scripts/rvm; cd $APP_ROOT"
CMD="$SET_PATH; bundle exec unicorn $UNICORN_OPTS"

sig () {
test -s "$PID" && kill -$1 `cat $PID`
}

case ${1-help} in
start)
sig 0 && echo >&2 "Already running" && exit 0
su - $APP_USER -c "$CMD"
;;
stop)
sig QUIT && exit 0
echo >&2 "Not running"
;;
force-stop)
sig TERM && exit 0
echo >&2 "Not running"
;;
restart)
sig QUIT && echo stopped OK
su - $APP_USER -c "$CMD" && exit 0
echo >&2 "Couldn't restart"
;;
reload)
sig USR2 && echo "wait for start new daemon" && exit 0
echo >&2 "Couldn't 'hot'-reload, try to restart instead"
;;
*)
echo >&2 "Usage: $0 <start|stop|restart|reload|force-stop>"
exit 1
;;
esac